### PR TITLE
Fix for #1854

### PR DESCRIPTION
**Pull request by pavel**
Solution:
Wait for 200ms, and then check if the file exists.
And when the file is gone, unwatch it.

### CODE REVIEW

**Comment by TimothyGu** [comment]
LGTM. @ForbesLindesay any comments?

**Comment by ForbesLindesay** [comment]
Can't we just keep watching it forever?  That 200ms timeout is a very arbitrary time, and I don't really see the problem with just continuing to watch it indefinitely.  It wastes a tiny bit of resources, but only in development and you can always restart the CLI if it becomes a serious problem.

**Comment by pavel** [comment]
Yep, that sounds reasonable. I'll fix and update.

**Comment by pavel** [comment]
@ForbesLindesay @TimothyGu 
Do we need to suppress ENOENT errors? They happen when a watched file has gone, that pops frequently when editing with VIM.

**Comment by TimothyGu** [comment]
@pavel, @ForbesLindesay meant to just remove the unwatching routine. It's kind of hard to fix.

**Comment by ForbesLindesay** [comment]
We probably should wrap the fs.readFileSync in a try catch and ignore ENOENT errors but only when it's as a result of a watch triggering.

**Comment by TimothyGu** [comment]
Thanks!

**Comment by ForbesLindesay** [comment]
Can we add a test case for this? Then remove the additional Istanbul annotation?

**Comment by TimothyGu** [comment]
@ForbesLindesay Already removed 1 minute before your comment: db894a1c5df0b85302c9a7ce66c67037ee347c72

I'll work on adding a test.

**Pull request merged**
