### PR TITLE
added new logo to the header and tweaked the link color to match

### PR DESCRIPTION
**Pull request by GarthDB**

### CODE REVIEW

**Comment by TimothyGu** [comment]
@GarthDB thanks! Can't wait for the new styles to be deployed.

**Comment by ForbesLindesay** [comment]
I second that,  I'll see about deploying soon :)

**Comment by GarthDB** [comment]
I have a better logo for the readme in the docs folder, once it's deployed we can update it.

**Comment by GarthDB** [comment]
Here's a screenshot until it gets deployed, in case anyone wanted a preview.

image

**Pull request merged**
