### PR TITLE
fix documentation, see https://github.com/jadejs/jade/issues/1970

### PR DESCRIPTION
**Pull request by alubbe**
I know we don't want PRs for this, but my reason is to ask how to handle small doc updates like this.
Should I just re-run the script? Should I go directly into gh-pages and update manually?

Maybe we can write down our findings into a Contributing.md. I'm willing to get it started :)

### CODE REVIEW

**Comment by TimothyGu** [comment]
> Should I just re-run the script? Should I go directly into gh-pages and update manually?

No, we usually rerun the script when a release is made.

> Maybe we can write down our findings into a Contributing.md. I'm willing to get it started :)

That would be great! (Also there might be an issue related to this)

**Comment by alubbe** [comment]
So we don't "fix" the docs/the website until the next release? I think it would be great to have a way of updating a specific version's docs even after its release. For example, the 1.10.0 release is still missing the new transformer options.

**Comment by TimothyGu** [comment]
> So we don't "fix" the docs/the website until the next release?

The rule is not "hard" so if you see a need for the fix, sure! I was just saying that we don't usually do this for convenience's sake.

**Comment by TimothyGu** [comment]
LGTM BTW.

**Comment by alubbe** [comment]
I'll merge and publish. Proposal for our policies is at https://github.com/jadejs/jade/pull/1981

@ForbesLindesay Could I interest you in documenting the new transformer options? :)

**Pull request merged**
