### PR TITLE
Re-render all base files for a dependency

### PR DESCRIPTION
**Pull request by richardgoater**
Keep an array of base paths per dependency.
Loop over and render each base when dependency changes.

A simple fix for a problem I was having with the watcher - let me know if I need to do anything else or if I'm completely mistaken :)

### CODE REVIEW

**Comment by TimothyGu** [comment]
Thanks for doing this. This is #1888, and I remember that I did have a patch for that bug. But now seems like I can't find that branch any more…

This pull request is a little bit more convoluted than it needs to be. For example, `watchList` and `watchDependencies` can just be one object. I'll make a new patch and let's see if my approach is a little bit easier to read :)

**Comment by TimothyGu** [comment]
Okay, new PR with tests at #1968. I believe that one is a lot simpler, but feel free to comment there.

I'll keep this PR open for now.

**Comment by richardgoater** [comment]
Hi @TimothyGu, yes that looks much better! Nice tests also, thanks very much for doing this. I'd really appreciate it if you could credit me for the initial implementation in the changelog please, and feel free to close this PR.

**Comment by TimothyGu** [comment]
Totally. I've updated the PR over there, so I'm going to close this one now.

**Pull request closed without merging**
