### PR TITLE
Do not ignore bracketExpression() errors

### PR DESCRIPTION
**Pull request by TimothyGu**
Improves stack traces. I am not sure why it was ignored in the first place. "not an interpolation expression, just an unmatched open interpolation" doesn't make any sense to me. Isn't an unmatched open interpolation bad?

Before:

```
Warning: missing space before text for line 1 of jade file "test/anti-cases/unclosed-interpolated-call.jade"

/home/timothy_gu/jade/lib/index.js:120
      throw err;
            ^
Error: The end of the string was reached with no closing bracket found.

Please report this entire error and stack trace to https://github.com/jadejs/jade/issues
    at parseMax (/home/timothy_gu/jade/node_modules/character-parser/index.js:26:13)
    at Object.Compiler.buffer (/home/timothy_gu/jade/lib/compiler.js:119:23)
    at Object.Compiler.visitText (/home/timothy_gu/jade/lib/compiler.js:521:10)
    at Object.Compiler.visitNode (/home/timothy_gu/jade/lib/compiler.js:225:37)
    at Object.Compiler.visit (/home/timothy_gu/jade/lib/compiler.js:212:10)
    at Object.Compiler.visitBlock (/home/timothy_gu/jade/lib/compiler.js:295:12)
    at Object.Compiler.visitNode (/home/timothy_gu/jade/lib/compiler.js:225:37)
    at Object.Compiler.visit (/home/timothy_gu/jade/lib/compiler.js:212:10)
    at Object.Compiler.compile (/home/timothy_gu/jade/lib/compiler.js:66:10)
    at parse (/home/timothy_gu/jade/lib/index.js:112:19)
```

After:

```
/home/timothy_gu/jade/lib/runtime.js:231
  throw err;
        ^
Error: test/anti-cases/unclosed-interpolated-call.jade:1
  > 1| +#{myMixin

The end of the string was reached with no closing bracket found.
    at Function.parseMax (/home/timothy_gu/jade/node_modules/character-parser/index.js:26:13)
    at Object.Lexer.bracketExpression (/home/timothy_gu/jade/lib/lexer.js:129:33)
    at Object.Lexer.call (/home/timothy_gu/jade/lib/lexer.js:454:26)
    at Object.Lexer.next (/home/timothy_gu/jade/lib/lexer.js:903:15)
    at Object.Lexer.lookahead (/home/timothy_gu/jade/lib/lexer.js:113:46)
    at Parser.lookahead (/home/timothy_gu/jade/lib/parser.js:102:23)
    at Parser.peek (/home/timothy_gu/jade/lib/parser.js:79:17)
    at Parser.parse (/home/timothy_gu/jade/lib/parser.js:117:26)
    at parse (/home/timothy_gu/jade/lib/index.js:102:21)
    at Object.exports.compile (/home/timothy_gu/jade/lib/index.js:203:16)
```

### CODE REVIEW

**Comment by ForbesLindesay** [comment]
Unfortunately I think this is a possible breaking change, so it may have to wait for 2.0.0  Other than that it's definitely great.

**Comment by ForbesLindesay** [comment]
We should at least add warnings for the unmatched brackets cases

**Comment by TimothyGu** [comment]
@ForbesLindesay Can you give an example of such breakage? I do not think any unmatched brackets work right now.

**Comment by ForbesLindesay** [comment]
Ah, the only one I can find is doing it in an attribute value (e.g. `p(foo="#{bar")`) but that still works after your change so I'm merging this now.

**Pull request merged**
