### PR TITLE
Interpolation reference

### PR DESCRIPTION
**Pull request by enlore**
As cool as this feature is, I feel like it needs it's own reference
page.

Aimed at #1620 and #1813.

### CODE REVIEW

**Comment by TimothyGu** [comment]
You can probably remove and/or merge the chapter from https://github.com/jadejs/jade/blob/master/docs/views/reference/code.jade#L88-L128.

**Comment by enlore** [comment]
Ah. I was using the published content on the web as a reference.  I'm going to dig through the source a little harder as I do this.  How do you guys go about publishing changes to the site?

**Comment by TimothyGu** [comment]
@enlore, we usually deploy new documentation with every new release.

**Comment by TimothyGu** [comment]
@enlore thanks!

**Comment by enlore** [comment]
No prob.

**Comment by ForbesLindesay** [comment]
We should also think about adding some "see also" links to relevant places so people find this when they don't necessarily know what "interpolation" means.

**Pull request merged**
