### PR TITLE
test: Write to output file before trying to read HTML

### PR DESCRIPTION
**Pull request by TimothyGu**

### CODE REVIEW

**Comment by alubbe** [comment]
What's the motivation/rationale?

**Comment by TimothyGu** [comment]
If a test is new, we will be able to directly copy the test/output/blah.html to test/cases/ instead of the `readFileSync` blowing up before the rendering is done.

**Comment by alubbe** [comment]
Okay.
Maybe move the var declaration down as well.
Otherwise, LGTM
Am 12.08.2015 16:54 schrieb "Timothy Gu" <notifications@github.com>:

**Comment by TimothyGu** [comment]
> Maybe move the var declaration down as well.

Not sure why I hadn't done that...

**Comment by TimothyGu** [comment]
Merged in 477e54901dcee8737d94c885110161e75dc5e13e

**Pull request closed without merging**
