### PR TITLE
1.11.0

### PR DESCRIPTION
**Pull request by alubbe**
Proposed changelog:
- Added block code support (@alephyud)
- Improved runtime performance of mixins significantly (@alubbe)
- Better line number counting for pipeless text (@alephyud)

Anything missing?

### CODE REVIEW

**Comment by ForbesLindesay** [comment]
Looks good to me.

**Comment by TimothyGu** [comment]
LGTM to me as well. Just don't forget to update History.md :)

**Comment by alubbe** [comment]
Added a line about string escaping, released to npm and updated website.
Sorry about how that took a few extra commits, it's early morning ;)

**Comment by jeromew** [comment]
@alubbe maybe I am wrong, but you forgot to push the 1.11 tag (1.11 is not mentionned on https://github.com/jadejs/jade/releases)

**Comment by alubbe** [comment]
you aren't wrong at all, I was just very tired :)

**Pull request merged**
