### PR TITLE
no value attributes are rendered differently

### PR DESCRIPTION
**Pull request by leider**
depending on wether it is done via included mixin or directly.

see `<div ui-view></div>` in the example

### CODE REVIEW

**Comment by TimothyGu** [comment]
This has nothing to do with if a mixin is used.

For example, the following works:

```jade
doctype html

mixin attr-mixin
  head
  body
    div(ui-view)
html
  +attr-mixin()
```

The reason why this fails is that the mixin is in a different file not declared with `doctype html`.

**Comment by leider** [comment]
So there currently is no way of putting the fragment in its own file?

That is "sad". But it is not really a showstopper. For me it's ok if you close the PR and the corresponding PR.

**Comment by leider** [comment]
Now that is weird. This also works:

```jade
doctype html
include auxiliary/mixin-attr-no-value
html
  +attr-mixin()
```

Just moving the include below the doctype.

**Comment by TimothyGu** [comment]
I am going to close this, since #1918 is still opened. Also, you can use the `doctype` option to work around the bug:

```jade
include auxiliary/mixin-attr-no-value
doctype html
html
  +attr-mixin()
```

```sh
$ jade --doctype html attr-no-value-mixin.jade
```

```js
var jade = require('jade')
var fs = require('fs')

jade.renderFile('attr-no-value-mixin.jade', { doctype: 'html' })
```

**Pull request closed without merging**
