### PR TITLE
Prettier logo for the README

### PR DESCRIPTION
**Pull request by TimothyGu**
Before:

[Jade - template engine](http://jade-lang.com/)

(https://github.com/jadejs/jade/blob/master/README.md#readme)

After:

[Jade - Node.js template engine](http://jade-lang.com/)

(https://github.com/jadejs/jade/blob/logo/README.md#readme)

See #1785.

### CODE REVIEW

**Comment by TimothyGu** [comment]
More info:

"jade" -- font: Futura Std Heavy (obtained from ~~http://valid.URL/~~ a very dependable free resource for fonts)

"Node Template Engine" -- font: Nimbus Sans L (I don't have Helvetica) (obtained from http://archive.ubuntu.com/ubuntu/pool/main/g/ghostscript/libgs9-common_9.10~dfsg-0ubuntu10_all.deb)

**Comment by jbnicolai** [comment]
Nice! :+1:

**Comment by TimothyGu** [comment]
New variants with more modern shadows:

Variant 1:
[Jade - Node.js template engine](http://jade-lang.com/)

Variant 2 (smaller but bolder shadow):
[Jade - Node.js template engine](https://github.com/TimothyGu/test/blob/gh-pages/JadeBlack.svg)

Variant 3 (*y*-axis shadow only, like Material Design):
[Jade - Node.js template engine](https://github.com/TimothyGu/test/blob/gh-pages/JadeBlackStraight.svg)

I personally prefer 3.

**Comment by hemanth** [comment]
Variant 3 is pretty appealing :dancer:

**Comment by TimothyGu** [comment]
@hemanth I just changed the main color of 4 to pure black. Hope this harmonizes with the GitHub style a little better.

**Comment by hemanth** [comment]
:+1:

**Comment by jbnicolai** [comment]
4 is my current favorite, but I'd consider any of them an improvement :smile:

@TimothyGu don't forget to rebase out the work-in-progress commits :wink:

**Comment by TimothyGu** [comment]
@jbnicolai Yeah I will once a final design is chosen.

**Comment by rlidwka** [comment]
> 4 is my current favorite, but I'd consider any of them an improvement

I have the same opinion here.

**Comment by ForbesLindesay** [comment]
I think 4 is my favourite as well, but I really don't mind.

**Pull request closed without merging**
